### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bhavyathakkarz** [Pika1998/face-recognition-login-system#4]
I'm getting the internal server error after I click on login button
![image](https://user-images.githubusercontent.com/76937947/158026170-cddd4ea0-8a6b-40f5-a2c5-4ea2f33f147a.png)

**Comment by prafulla-codes** [comment]
Hey @bhavyathakkarz , kindly refer the below issue, this is already discussed here - https://github.com/prafulla-codes/face-recognition-login-system/issues/3
